apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "forest"
  namespace: team-a
spec:
  predictor:
    serviceAccountName: kserve-sa
    annotations:
      prometheus.kserve.io/port: "8080"
      prometheus.kserve.io/path: /metrics
    minReplicas: 1
    maxReplicas: 5
    model:
      modelFormat:
        name: sklearn
      storageUri: "s3://kserve-cluster-model-artifacts-768871556035/2/models/m-1fb354af8be94b34987e3fb29e102435/artifacts"
      resources:
        requests:
          cpu: "100m"
          memory: "512Mi"
        limits:
          cpu: "1"
          memory: "1Gi"